/* Revoke */
--TABLE
REVOKE DELETE ON WSMBATCH.TINTRBILL FROM userall
go
REVOKE INSERT ON WSMBATCH.TINTRBILL FROM userall
go
REVOKE SELECT ON WSMBATCH.TINTRBILL FROM userall
go
REVOKE UPDATE ON WSMBATCH.TINTRBILL FROM userall
go
REVOKE REFERENCES ON WSMBATCH.TINTRBILL FROM userall
go

--SP
REVOKE EXECUTE ON WSMBATCH.E2BILLING FROM userall
go