/* Revoke */
--TABLE
REVOKE DELETE ON DMBATCH.TINTRBILL FROM userall
go
REVOKE INSERT ON DMBATCH.TINTRBILL FROM userall
go
REVOKE SELECT ON DMBATCH.TINTRBILL FROM userall
go
REVOKE UPDATE ON DMBATCH.TINTRBILL FROM userall
go
REVOKE REFERENCES ON DMBATCH.TINTRBILL FROM userall
go

--SP
REVOKE EXECUTE ON DMBATCH.E2BILLING FROM userall
go