/* Grant */
--TABLE
GRANT DELETE ON DMBATCH.TINTRBILL TO userall
go
GRANT INSERT ON DMBATCH.TINTRBILL TO userall
go
GRANT SELECT ON DMBATCH.TINTRBILL TO userall
go
GRANT UPDATE ON DMBATCH.TINTRBILL TO userall
go
GRANT REFERENCES ON DMBATCH.TINTRBILL TO userall
go

--SP
GRANT EXECUTE ON DMBATCH.E2BILLING TO userall
go