/* Grant */
--TABLE
GRANT DELETE ON WSMBATCH.TINTRBILL TO userall
go
GRANT INSERT ON WSMBATCH.TINTRBILL TO userall
go
GRANT SELECT ON WSMBATCH.TINTRBILL TO userall
go
GRANT UPDATE ON WSMBATCH.TINTRBILL TO userall
go
GRANT REFERENCES ON WSMBATCH.TINTRBILL TO userall
go

--SP
GRANT EXECUTE ON WSMBATCH.E2BILLING TO userall
go