SELECT A.POLICYCERT_NO, a.ANN_PREMIUM_AMT, H.PHOLD_FAMILY_NAME,  H.phold_mobil_no, h.PHOLD_HOME_NO, E.BSB_NO, F.BILLING_ORG_CD, F.BILLING_ORG_NAME
INTO #TMP_POL
FROM TPOLICYCERT A, TPOLICYCERTRIDER R, tpolicycertholder H, tbillorg F, tpaymentdets E
where A.POLICYCERT_NO=R.POLICYCERT_NO
AND R.LATEST_VERSION_FG='Y'
AND A.POLICY_HOLDER_NO=H.POLICY_HOLDER_NO
AND A.BILLING_ORG_CD=F.BILLING_ORG_CD
AND A.POLICYCERT_NO=E.POLICYCERT_NO
AND E.LATEST_VERSION_FG='Y'
--AND E.BSB_NO='000009'
--AND R.PLAN_NO=PL.PLAN_NO
--AND R.CAMPAIGN_CD=C.CAMPAIGN_CD
AND A.STATUS_CD='A'
group BY A.POLICYCERT_NO, a.ANN_PREMIUM_AMT, H.PHOLD_FAMILY_NAME,  H.phold_mobil_no, h.PHOLD_HOME_NO, E.BSB_NO, F.BILLING_ORG_CD, F.BILLING_ORG_NAME


SELECT b.POLICYCERT_NO,b.ANN_PREMIUM_AMT,  b.PHOLD_FAMILY_NAME,  b.phold_mobil_no, b.PHOLD_HOME_NO, b.BSB_NO, b.BILLING_ORG_CD, b.BILLING_ORG_NAME,  max(a.COLLECTED_DATE) FROM tbilltrxn a
INNER JOIN #TMP_POL b
ON a.POLICYCERT_NO = b.POLICYCERT_NO
WHERE a.COLLECTED_FG = 'Y'
GROUP BY b.POLICYCERT_NO,b.ANN_PREMIUM_AMT,  b.PHOLD_FAMILY_NAME,  b.phold_mobil_no, b.PHOLD_HOME_NO, b.BSB_NO, b.BILLING_ORG_CD, b.BILLING_ORG_NAME


DROP TABLE #TMP_POL
GO
