--创建统计数据表
CREATE TABLE #TMP_AMT(
	TYPE_C             VARCHAR(50),
	POLICY_COUNT       INT,
	POLICYCERT_NO      VARCHAR(50),
	POLICY_EFF_DATE    DATETIME,
	PREMIUM_AMT        MONEY
)
GO

--符合生效保单
SELECT
TPOLICYCERT.POLICYCERT_NO
,TPOLICYCERTRIDER.POLICY_EFF_DATE
,TPOLICYCERTRIDER.STATUS_CD
,TPRODUCTDETS.PRODUCT_NAME
,TPOLICYCERTPREMIUM.PLAN_NO
,TPOLICYCERTPREMIUM.PREMIUM_AMT
,TPAYMENTDETS.BILL_INTERVAL_CD
,TNAMEDINSURED.NAM_INS_FAM_NAME
,convert(char(10), TNAMEDINSURED.NAM_INS_BIRTH_DATE, 111) AS NAM_INS_BIRTH_DATE
,ISNULL(TPOLICYCERTPREMIUM.BENEFIT_AMT,0) AS BENEFIT_AMT
INTO #TMP_POLICY_TMP
FROM TPOLICYCERT
JOIN TNAMEDINSURED ON TNAMEDINSURED.POLICYCERT_NO = TPOLICYCERT.POLICYCERT_NO
JOIN TPOLICYCERTRIDER ON TPOLICYCERTRIDER.POLICYCERT_NO = TNAMEDINSURED.POLICYCERT_NO
	AND TPOLICYCERTRIDER.END_EFF_DATE = TNAMEDINSURED.END_EFF_DATE
	AND TPOLICYCERTRIDER.RIDER_NO = TNAMEDINSURED.RIDER_NO
	AND TPOLICYCERTRIDER.LANGUAGE_CD = 0
JOIN TPOLICYCERTPREMIUM ON TPOLICYCERTPREMIUM.POLICYCERT_NO = TNAMEDINSURED.POLICYCERT_NO
	AND TPOLICYCERTPREMIUM.END_EFF_DATE = TNAMEDINSURED.END_EFF_DATE
	AND TPOLICYCERTPREMIUM.NAME_INSURED_NO = TNAMEDINSURED.NAME_INSURED_NO
	AND TPOLICYCERTPREMIUM.RIDER_NO = TNAMEDINSURED.RIDER_NO
	AND TPOLICYCERTPREMIUM.LATEST_VERSION_FG = 'Y'
JOIN TPRODUCTDETS ON TPRODUCTDETS.PRODUCT_CD = TPOLICYCERTPREMIUM.PRODUCT_CD
LEFT JOIN TCAMPDETS
ON TCAMPDETS.CAMPAIGN_CD = TPOLICYCERTRIDER.CAMPAIGN_CD
LEFT JOIN TSPONSORDETS
ON TSPONSORDETS.SPONSOR_NO = TCAMPDETS.SPONSOR_NO
LEFT JOIN TPAYMENTDETS
ON TPAYMENTDETS.POLICYCERT_NO = TPOLICYCERTPREMIUM.POLICYCERT_NO
AND TPAYMENTDETS.LATEST_VERSION_FG = 'Y'
WHERE 1=1
--生效保单
AND TPOLICYCERTRIDER.LATEST_VERSION_FG = 'Y'
AND TPOLICYCERTRIDER.CANCEL_DATE IS NULL
AND TPOLICYCERTRIDER.STATUS_CD = 'a'


--取得有效期最近的险种和计划
SELECT TPL.PRODUCT_CD,TPL.PLAN_NO,TPL.END_EFF_DATE
INTO #TMP_PPROD
FROM (
SELECT PLAN_NO, MAX(END_EFF_DATE) AS END_EFF_DATE
FROM TPLANPRODUCT
GROUP BY  PLAN_NO) T
INNER JOIN TPLANPRODUCT TPL
ON T.PLAN_NO = TPL.PLAN_NO
AND T.END_EFF_DATE = TPL.END_EFF_DATE


--获取副险险种产品
SELECT 
	P.POLICYCERT_NO
	,P.POLICY_EFF_DATE
	,P.STATUS_CD
	,PR.PRODUCT_CD
	,P.PRODUCT_NAME
	,P.PLAN_NO
	,P.PREMIUM_AMT
	,P.BILL_INTERVAL_CD
	,P.NAM_INS_FAM_NAME
    ,P.NAM_INS_BIRTH_DATE
	,P.BENEFIT_AMT
INTO #TMP_POLICY
FROM #TMP_POLICY_TMP P
INNER JOIN #TMP_PPROD PR
ON P.PLAN_NO = PR.PLAN_NO

DROP TABLE #TMP_POLICY_TMP
GO

--计算保费
UPDATE #TMP_POLICY 
SET P.PREMIUM_AMT =
(CASE WHEN P.BILL_INTERVAL_CD = 'A' THEN
	 P.PREMIUM_AMT * (PP.PREM_ALLOC_PCT / 100) 
     WHEN P.BILL_INTERVAL_CD = 'M' THEN
	 P.PREMIUM_AMT * 12 * (PP.PREM_ALLOC_PCT / 100) 
END)
FROM #TMP_POLICY P
INNER JOIN #TMP_PPROD T
ON P.PRODUCT_CD = T.PRODUCT_CD
AND P.PLAN_NO = T.PLAN_NO
INNER JOIN TPLANPRODUCT PP
ON PP.PRODUCT_CD = T.PRODUCT_CD
AND PP.PLAN_NO = T.PLAN_NO
AND PP.END_EFF_DATE = T.END_EFF_DATE 

--统计年缴保单数量
INSERT INTO #TMP_AMT 
SELECT 
'年缴保单'
,COUNT(DISTINCT POLICYCERT_NO)
,'Pol'
,getdate()
,1
FROM #TMP_POLICY
WHERE BILL_INTERVAL_CD = 'A'

--统计月缴保单数量
INSERT INTO #TMP_AMT 
SELECT 
'月缴保单'
,COUNT(DISTINCT POLICYCERT_NO)
,'Pol'
,getdate()
,1
FROM #TMP_POLICY
WHERE BILL_INTERVAL_CD = 'M'

--统计年缴保单最高保费
SELECT 
TOP 1
POLICYCERT_NO
,POLICY_EFF_DATE
,PREMIUM_AMT
,TYPE_C
INTO #TMP_A
FROM
(SELECT 
	POLICYCERT_NO
	,POLICY_EFF_DATE
	,SUM(PREMIUM_AMT) AS PREMIUM_AMT
	,'年缴保单' AS TYPE_C
FROM #TMP_POLICY
WHERE BILL_INTERVAL_CD = 'A'
GROUP BY POLICYCERT_NO, POLICY_EFF_DATE
)TMP_P
ORDER BY PREMIUM_AMT DESC

UPDATE #TMP_AMT 
SET POLICYCERT_NO = #TMP_A.POLICYCERT_NO
,POLICY_EFF_DATE = #TMP_A.POLICY_EFF_DATE
,PREMIUM_AMT = #TMP_A.PREMIUM_AMT
FROM #TMP_A
WHERE  #TMP_AMT.TYPE_C = #TMP_A.TYPE_C


--统计月缴保单最高保费
SELECT 
TOP 1
POLICYCERT_NO
,POLICY_EFF_DATE
,PREMIUM_AMT
,TYPE_C
INTO #TMP_M
FROM
(SELECT 
	POLICYCERT_NO
	,POLICY_EFF_DATE
	,SUM(PREMIUM_AMT) AS PREMIUM_AMT
	,'月缴保单' AS TYPE_C
FROM #TMP_POLICY
WHERE BILL_INTERVAL_CD = 'M'
GROUP BY POLICYCERT_NO, POLICY_EFF_DATE
)TMP_P
ORDER BY PREMIUM_AMT DESC
	
UPDATE #TMP_AMT 
SET POLICYCERT_NO = #TMP_M.POLICYCERT_NO
,POLICY_EFF_DATE = #TMP_M.POLICY_EFF_DATE
,PREMIUM_AMT = #TMP_M.PREMIUM_AMT
FROM #TMP_M
WHERE  #TMP_AMT.TYPE_C = #TMP_M.TYPE_C

--统计结果
SELECT
TYPE_C              AS '分类'
,POLICY_COUNT       AS '保单数量'
,POLICYCERT_NO      AS '保单号'
,POLICY_EFF_DATE    AS '生效日期'
,PREMIUM_AMT        AS '最高保费'
FROM #TMP_AMT 

--删除临时表
DROP TABLE #TMP_M
DROP TABLE #TMP_A
DROP TABLE #TMP_POLICY
DROP TABLE #TMP_PPROD
DROP TABLE #TMP_AMT
GO