
--Active Policy
SELECT * INTO #TMP_POL_AC FROM TPOLICYCERT WHERE STATUS_CD = 'A'

--FIND THE NEWEST END_EFF_DATE OF ACT POLICY
SELECT P.policycert_no,MAX(END_EFF_DATE) AS MAX_END_EFF_DATE
INTO #TMP_MAX_EFF
FROM TPAYMENTDETS P, #TMP_POL_AC T
WHERE P.policycert_no = T.policycert_no
GROUP BY P.policycert_no

--FIND DATA THAT ACCOUNT NO STARTS WITH 3,4,5
SELECT P.policycert_no,LTRIM(P.ACCOUNT_NO) AS ACCOUNT_NO,LEFT(LTRIM(P.ACCOUNT_NO),1) AS ACC_1
INTO #TMP_ACC45
FROM TPAYMENTDETS P,#TMP_MAX_EFF T
WHERE P.policycert_no = T.policycert_no
AND P.END_EFF_DATE = T.MAX_END_EFF_DATE
AND DATALENGTH(RTRIM(STR_REPLACE(STR_REPLACE(P.ACCOUNT_NO,' ',''),'-','')))  BETWEEN 14 AND 19
AND LEFT(LTRIM(P.ACCOUNT_NO),1) IN ('3','4','5')

 
 
SELECT t.POLICYCERT_NO,t.POLICY_HOLDER_NO ,ACC.ACC_1,ACC.ACCOUNT_NO,
PH.PHOLD_FAMILY_NAME, PH.PHOLD_HOME_NO, PH.PHOLD_EMAIL, PH.PHOLD_1_ADDR, PH.PHOLD_2_ADDR, PH.PHOLD_3_ADDR, PH.PHOLD_4_ADDR
FROM #TMP_POL_AC T,#TMP_ACC45 ACC,TPOLICYCERTHOLDER PH
WHERE T.POLICYCERT_NO = ACC.POLICYCERT_NO
AND t.POLICY_HOLDER_NO = PH.POLICY_HOLDER_NO 
 

DROP TABLE #TMP_POL_AC
DROP TABLE #TMP_MAX_EFF
DROP TABLE #TMP_ACC45
 