--1.	请拉取 2020年8月1号至8月31号 保单将到期续保的 在保DM&VEB保单清单，即每月月头拉取下个月到期续保的保单清单，

--SELECT POLICY_REN_DATE,* FROM TPOLICYCERTRIDER  WHERE
SELECT A.POLICYCERT_NO, R.POLICY_EFF_DATE, H.PHOLD_FAMILY_NAME,H.Social_sec_no, H.PHOLD_EMAIL, PL.PLAN_NAME, C.SPONSOR_NAME, A.ANN_PREMIUM_AMT, H.phold_home_no, H.phold_mobil_no, A.billing_org_cd,F.BILLING_ORG_NAME
,max(COLLECTED_DATE) as latest_COLLECTED_DATE
FROM TPOLICYCERT A, TPOLICYCERTRIDER R, tpolicycertholder H, tbillorg F, tpaymentdets E, tplandets pl, TCAMPDETS C,TBILLTRXN t1
where A.POLICYCERT_NO=R.POLICYCERT_NO
AND R.LATEST_VERSION_FG='Y'
AND A.POLICY_HOLDER_NO=H.POLICY_HOLDER_NO
AND A.BILLING_ORG_CD=F.BILLING_ORG_CD
--AND F.BILLING_ORG_CD IN ('BJ0003','JS0001','SH0016','ZJ0001','GZ0007')
AND A.POLICYCERT_NO=E.POLICYCERT_NO
AND E.LATEST_VERSION_FG='Y'
--AND E.BSB_NO='000009'
AND R.PLAN_NO=PL.PLAN_NO
AND R.CAMPAIGN_CD=C.CAMPAIGN_CD
AND A.STATUS_CD='A'
--and A.POLICYCERT_NO='GZ050000000017'
and t1.POLICYCERT_NO=a.POLICYCERT_NO
and t1.COLLECTED_FG='y'
and r.POLICY_REN_DATE between '2020-12-01' and '2020-12-31'
group BY A.POLICYCERT_NO, R.POLICY_EFF_DATE, H.PHOLD_FAMILY_NAME,H.Social_sec_no, H.PHOLD_EMAIL, PL.PLAN_NAME, C.SPONSOR_NAME, A.ANN_PREMIUM_AMT, H.phold_home_no, H.phold_mobil_no, A.billing_org_cd,F.BILLING_ORG_NAME
