--符合时间保单
SELECT
TPOLICYCERT.POLICYCERT_NO
,TPOLICYCERTRIDER.POLICY_EFF_DATE
,TPOLICYCERTRIDER.STATUS_CD
,TPOLICYCERTRIDER.CANCEL_DATE												
,TPRODUCTDETS.PRODUCT_NAME 											    
,ISNULL(TPOLICYCERTPREMIUM.BENEFIT_AMT,0) AS BENEFIT_AMT                                 
,TNAMEDINSURED.NAME_INSURED_NO                                                           
,TPOLICYCERTPREMIUM.PLAN_NO 
,TPOLICYCERTPREMIUM.PREMIUM_AMT
,TNAMEDINSURED.NAM_INS_FAM_NAME							                            
,convert(char(10), TNAMEDINSURED.NAM_INS_BIRTH_DATE, 111) AS NAM_INS_BIRTH_DATE		
,TNAMEDINSURED.SEX_CD                                                               
,TSPONSORDETS.SPONSOR_NAME  
,TPAYMENTDETS.BILL_INTERVAL_CD                                                  
INTO #TMP_POLICY_TMP
FROM TPOLICYCERT
JOIN TNAMEDINSURED ON TNAMEDINSURED.POLICYCERT_NO = TPOLICYCERT.POLICYCERT_NO
JOIN TPOLICYCERTRIDER ON TPOLICYCERTRIDER.POLICYCERT_NO = TNAMEDINSURED.POLICYCERT_NO
	AND TPOLICYCERTRIDER.END_EFF_DATE = TNAMEDINSURED.END_EFF_DATE
	AND TPOLICYCERTRIDER.RIDER_NO = TNAMEDINSURED.RIDER_NO
	AND TPOLICYCERTRIDER.LANGUAGE_CD = 0					
JOIN TPOLICYCERTPREMIUM ON TPOLICYCERTPREMIUM.POLICYCERT_NO = TNAMEDINSURED.POLICYCERT_NO
	AND TPOLICYCERTPREMIUM.END_EFF_DATE = TNAMEDINSURED.END_EFF_DATE
	AND TPOLICYCERTPREMIUM.NAME_INSURED_NO = TNAMEDINSURED.NAME_INSURED_NO
	AND TPOLICYCERTPREMIUM.RIDER_NO = TNAMEDINSURED.RIDER_NO
JOIN TPRODUCTDETS ON TPRODUCTDETS.PRODUCT_CD = TPOLICYCERTPREMIUM.PRODUCT_CD
LEFT JOIN TCAMPDETS 
ON TCAMPDETS.CAMPAIGN_CD = TPOLICYCERTRIDER.CAMPAIGN_CD
LEFT JOIN TSPONSORDETS
ON TSPONSORDETS.SPONSOR_NO = TCAMPDETS.SPONSOR_NO
LEFT JOIN TPAYMENTDETS 
ON TPAYMENTDETS.POLICYCERT_NO = TPOLICYCERTPREMIUM.POLICYCERT_NO
AND TPAYMENTDETS.LATEST_VERSION_FG = 'Y'
WHERE 1=1
--保单生效日期
-AND 
(TPOLICYCERTRIDER.POLICY_EFF_DATE >='2015/01/01 00:00:00'
AND TPOLICYCERTRIDER.POLICY_EFF_DATE <='2015/12/31 23:59:59')
AND TPOLICYCERTPREMIUM.LATEST_VERSION_FG = 'Y'
AND TPOLICYCERT.BILLING_ORG_CD IN ('BJ0001',
'BJ0003',
'FS0002',
'GZ0168',
'SH0100',
'SH0101',
'SH124',
'SH133',
'SZB002',
'SZ0176',
'SZB004',
'SZ0181',
'SZ0172',
'FS0026',
'GZ0014',
'GZ0016',
'SH0007',
'SH0023',
'SH0065',
'SZ0057',
'SZ0180',
'SZ0179',
'BJ0008')
AND TPOLICYCERT.POLICYCERT_NO='BJ025000001194'


--取得有效期最近的险种和计划
SELECT TPL.PRODUCT_CD,TPL.PLAN_NO,TPL.END_EFF_DATE
INTO #TMP_PPROD
FROM (
SELECT PLAN_NO, MAX(END_EFF_DATE) AS END_EFF_DATE
FROM TPLANPRODUCT
GROUP BY  PLAN_NO) T
INNER JOIN TPLANPRODUCT TPL
ON T.PLAN_NO = TPL.PLAN_NO
AND T.END_EFF_DATE = TPL.END_EFF_DATE


--取得有效期最近的产品名称
SELECT PLAN_NO, MAX(END_EFF_DATE) AS END_EFF_DATE
INTO #TMP_PLAN_NO
FROM TPLANDETS
GROUP BY PLAN_NO

SELECT PL.PLAN_NO, PL.END_EFF_DATE, PD.PLAN_NAME
INTO #TMP_PLAN_NAME
FROM #TMP_PLAN_NO PL
INNER JOIN TPLANDETS PD
ON PL.PLAN_NO = PD.PLAN_NO
AND PL.END_EFF_DATE = PD.END_EFF_DATE

DROP TABLE #TMP_PLAN_NO

--取得有效期最近的计划的所有保额
SELECT PLAN_NO, PRODUCT_CD, MAX(END_EFF_DATE) AS END_EFF_DATE
INTO #TMP_PLAN_BENEFITS
FROM TPLANBENEFITS
WHERE SORT_BEN_PLAN_NO = 1
GROUP BY  PLAN_NO, PRODUCT_CD

SELECT DISTINCT PD.PLAN_NO, PD.PRODUCT_CD, PD.BENEFIT_AMT, PD.END_EFF_DATE
INTO #TMP_PLAN_RELBENEFITS
FROM #TMP_PLAN_BENEFITS PL
INNER JOIN TPLANBENEFITS PD
ON PL.PLAN_NO = PD.PLAN_NO
AND PL.PRODUCT_CD = PD.PRODUCT_CD
AND PL.END_EFF_DATE = PD.END_EFF_DATE
AND PD.SORT_BEN_PLAN_NO = 1

DROP TABLE #TMP_PLAN_BENEFITS

--获取副险险种产品
SELECT 
	P.POLICYCERT_NO
	,P.POLICY_EFF_DATE
	,P.STATUS_CD
	,P.CANCEL_DATE
	,PR.PRODUCT_CD												
	,P.PRODUCT_NAME 											    
	,P.BENEFIT_AMT                                 
	,P.NAME_INSURED_NO                                                           
	,P.PLAN_NO 
	,P.PREMIUM_AMT
	,P.NAM_INS_FAM_NAME							                            
	,P.NAM_INS_BIRTH_DATE		
	,P.SEX_CD                                                               
	,P.SPONSOR_NAME
	,P.BILL_INTERVAL_CD  
INTO #TMP_POLICY
FROM #TMP_POLICY_TMP P
INNER JOIN #TMP_PPROD PR
ON P.PLAN_NO = PR.PLAN_NO

DROP TABLE #TMP_POLICY_TMP

--计算保费
UPDATE #TMP_POLICY 
SET P.PREMIUM_AMT =
(CASE WHEN P.BILL_INTERVAL_CD = 'A' THEN
	 P.PREMIUM_AMT * (PP.PREM_ALLOC_PCT / 100) 
     WHEN P.BILL_INTERVAL_CD = 'M' THEN
	 P.PREMIUM_AMT * 12 * (PP.PREM_ALLOC_PCT / 100) 
END)
FROM #TMP_POLICY P
INNER JOIN #TMP_PPROD T
ON P.PRODUCT_CD = T.PRODUCT_CD
AND P.PLAN_NO = T.PLAN_NO
INNER JOIN TPLANPRODUCT PP
ON PP.PRODUCT_CD = T.PRODUCT_CD
AND PP.PLAN_NO = T.PLAN_NO
AND PP.END_EFF_DATE = T.END_EFF_DATE 

--计算保额
UPDATE #TMP_POLICY
SET P.BENEFIT_AMT = T.BENEFIT_AMT
FROM #TMP_POLICY P
INNER JOIN #TMP_PLAN_RELBENEFITS T
ON P.PRODUCT_CD = T.PRODUCT_CD
AND P.PLAN_NO = T.PLAN_NO

SELECT 
P.POLICYCERT_NO         AS '保单号码'                        --Col1:保单号码
,P.POLICY_EFF_DATE      AS '生效日期'                        --Col2:生效日期
,P.STATUS_CD            AS '状态'                            --Col3:状态
,P.CANCEL_DATE          AS '取消日期'                        --Col4:取消日期
,P.PRODUCT_CD 			AS '险种代码'						 --Col5:险种代码			
,P.PRODUCT_NAME 		AS '险种名称'						 --Col6:险种名称		    
,P.BENEFIT_AMT          AS '保额'                            --Col7:保额
,P.PREMIUM_AMT          AS '保费'                            --Col8:保费
,P.NAM_INS_FAM_NAME		AS '被保险人名称'					 --Col9:被保险人名称
,P.NAM_INS_BIRTH_DATE 	AS '被保险人出生日期'			     --Col10:被保险人出生日期(yyyy/mm/dd)
,P.SEX_CD               AS '被保险人性别'                    --Col11:被保险人性别
,P.SPONSOR_NAME         AS '担保者'                          --Col12:担保者
,TPN.PLAN_NAME          AS '产品名称'                        --Col13:产品名称
FROM #TMP_POLICY P
LEFT JOIN #TMP_PLAN_NAME TPN
ON P.PLAN_NO = TPN.PLAN_NO


DROP TABLE #TMP_POLICY
DROP TABLE #TMP_PPROD
DROP TABLE #TMP_PLAN_NAME
DROP TABLE #TMP_PLAN_RELBENEFITS
